# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: check-toml
  - id: end-of-file-fixer

- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.1.0
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --preserve-quotes
    - --indent=2

- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
  - id: black
    name: format_with_black
    language_version: python3

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort
    name: sort_imports_with_isort
    args: ["--profile", "black"]

- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    args:
    - "--max-line-length=120"
    - "--max-complexity=18"
    - "--exclude=.tox,.git,venv"
    - "--select=B,C,E,F,W,T4,B9"
    - "--ignore=E203,E266,E501,W503,F403,F401,E402,F405,W605,F541,F841,C901,E711,E712"

- repo: local
  hooks:
  - id: autoflake
    name: autoflake
    entry: poetry run autoflake
    language: system
    types: [python]
    args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]
